title: FunkyBookends Bliki
theme: jekyll-theme-minimal
description: This is a place for me to track the interesting software engieering videos and posts that I have come across.
author: Capar Nonclercq
